export const CTREATE_POST = 'POST/CREATE_POST';
export const CREATE_FETCHED_POST = 'CREATE_FETCHED_POST';
export const CREATE_HOOKS_FETCHED_POST = 'CREATE_HOOKS_FETCHED_POST';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';